# Generated by Django 3.2.12 on 2022-07-05 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eskiz_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
