# Generated by Django 3.2.12 on 2022-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220706_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eksiz_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
