# Generated by Django 3.2.12 on 2022-06-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='likes',
        ),
    ]
