# Generated by Django 3.2.12 on 2022-07-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
