# Generated by Django 4.0.3 on 2022-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Mahsulotlar'),
        ),
    ]
