# Generated by Django 3.2.12 on 2022-07-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_450_200',
            field=models.ImageField(blank=True, default='banner_1.jpg', upload_to='', verbose_name='450x200'),
        ),
    ]
