# Generated by Django 3.2.12 on 2022-04-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20220425_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_135x135',
            field=models.ImageField(blank=True, default='images/135x135.jpg', upload_to='', verbose_name='135x135'),
        ),
    ]
