# Generated by Django 3.2.12 on 2022-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_alter_products_image_450_200'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=617, null=True)),
            ],
        ),
    ]
