# Generated by Django 4.0.3 on 2022-04-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('body', models.CharField(max_length=40, null=True)),
                ('mini_body', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(upload_to='', verbose_name='1920x500 rasm')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='myshop.reviews'),
        ),
    ]
