# Generated by Django 3.2.12 on 2022-06-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_customermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(null=True, verbose_name='mahsulot haqida qisqacha'),
        ),
    ]
