# Generated by Django 4.0.3 on 2022-04-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_sliderimage_alter_product_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('mini_body', models.CharField(max_length=30, null=True)),
                ('discount_info', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(upload_to='', verbose_name='450x200 rasm')),
            ],
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='mini_body',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
