# Generated by Django 3.2.12 on 2022-07-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
