# Generated by Django 3.2.12 on 2022-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_smsclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsclient',
            name='token',
            field=models.CharField(max_length=817, null=True),
        ),
    ]
