# Generated by Django 3.2.12 on 2022-07-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_alter_smsclient_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ordered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
