# Generated by Django 4.0.3 on 2022-04-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_bannerarea_alter_sliderimage_mini_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topsell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='topsell', verbose_name='1920x500 rasm')),
            ],
        ),
        migrations.AlterField(
            model_name='bannerarea',
            name='image',
            field=models.ImageField(upload_to='bannerArea', verbose_name='450x200 rasm'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='sliderImage', verbose_name='1920x500 rasm'),
        ),
    ]
