# Generated by Django 3.2.12 on 2022-07-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsclient',
            name='token',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
