# Generated by Django 3.2.12 on 2022-06-28 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myshop', '0006_cartmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartModel',
            new_name='Cart',
        ),
    ]
