# Generated by Django 4.0.3 on 2022-04-02 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_topsell_alter_bannerarea_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='topsell', verbose_name='396x396 rasm')),
            ],
        ),
        migrations.AddField(
            model_name='topsell',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myshop.categories'),
        ),
        migrations.AlterField(
            model_name='topsell',
            name='image',
            field=models.ImageField(upload_to='topsell', verbose_name='396x396 rasm'),
        ),
    ]
