# Generated by Django 3.2.12 on 2022-07-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_alter_smsclient_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='tag',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
