# Generated by Django 3.2.12 on 2022-07-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_products_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ordered',
        ),
    ]
