# Generated by Django 3.2.12 on 2022-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_categories_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='is_ordered'),
        ),
    ]
