# Generated by Django 4.0.3 on 2022-04-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_product_image2_product_image3_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_info',
            field=models.CharField(max_length=30, null=True, verbose_name="chegirma haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='product',
            name='mini_body',
            field=models.CharField(max_length=30, null=True, verbose_name="qisqacha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
    ]
