# Generated by Django 3.2.12 on 2022-07-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_auto_20220702_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=617, null=True)),
            ],
        ),
    ]
