# Generated by Django 4.0.3 on 2022-04-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_product_discount_info_product_mini_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mini_body',
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='450x200'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='600x600'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='828x828'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='1410x690'),
        ),
    ]
