# Generated by Django 4.0.3 on 2022-04-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_remove_product_mini_body_product_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mini_body',
            field=models.CharField(max_length=30, null=True, verbose_name="qisqacha ma'lumot"),
        ),
    ]
