# Generated by Django 3.2.12 on 2022-04-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_delete_bannerarea_delete_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='450x200'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='600x600'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='828x828'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='427x427'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='1410x690'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='1920x500 rasm'),
        ),
    ]
