name: Mysite CD


on:
  push:
    branches: [master]
  
  pull_request:
    branches: [master]

jobs:
  check-unit-tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULEL: configs.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: ${{ secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TELEBOT_URL: ${{ secrets.TELEBOT_URL }}
          TELEBOT_TOKEN: ${{ secrets.TELEBOT_TOKEN }}
          TELEBOT_CHAT_ID: ${{ secrets.TELEBOT_CHAT_ID }}
          TELEBOT_CHAT_ID_WARNINGS: ${{ secrets.TELEBOT_CHAT_ID_WARNINGS }}
          TELEBOT_CHAT_ID_ORDERS: ${{ secrets.TELEBOT_CHAT_ID_ORDERS }}
          POSTGRES_ENGINE: ${{ secrets.POSTGRES_ENGINE }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        run: python3 manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: check-unit-tests
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd alsafia
          git pull origin main
          systemctl restart gunicorn.service